export const SITE = {
  business: {
    name:      'Noir Studio',
    tagline:   'Hair, done differently.',
    phone:     '016 982 4471',
    whatsapp:  '27716824471',
    email:     'hello@noirstudio.co.za',
    address:   '14 Frikkie Meyer Blvd, Vanderbijlpark',
    area:      'Vanderbijlpark',
    instagram: '#',
    facebook:  '#',
    google:    '#',
    hours: [
      { day: 'Tuesday – Friday', time: '08:30 – 17:30' },
      { day: 'Saturday',         time: '08:30 – 15:00' },
      { day: 'Sunday & Monday',  time: 'Closed'         },
    ],
  },

  hero: {
    label:       'Est. 2016 · Vanderbijlpark, Gauteng',
    line1:       'Hair, done',
    line2:       'differently.',
    subheadline: 'Vanderbijlpark\'s premier hair atelier. Where craft meets confidence.',
    cta1:        'Book Your Appointment',
    cta2:        'Our Services',
    image:       'https://picsum.photos/1920/1080?random=33',
  },

  stats: [
    { value: '4.9', label: 'Google Rating'     },
    { value: '2k+', label: 'Happy Clients'     },
    { value: '8',   label: 'Years Experience'  },
  ],

  services: [
    {
      id: 1, num: '01',
      name: 'Signature Cut & Style',
      short: 'Precision cut tailored to your face shape, finished and styled to perfection.',
      description: 'Every cut starts with a consultation. Adéle studies your face shape, hair texture, and lifestyle before a single snip. The result is a cut that works for you every day — not just in the salon.',
      price: 'From R450', duration: '60 – 90 min',
    },
    {
      id: 2, num: '02',
      name: 'Colour & Balayage',
      short: 'Hand-painted colour and full-spectrum toning, from subtle to statement.',
      description: 'From seamless root blends to full transformations, our colour work is mixed and applied by hand using professional-grade colour that conditions while it processes. Toner and glossing included.',
      price: 'From R850', duration: '2 – 4 hours',
    },
    {
      id: 3, num: '03',
      name: 'Keratin Treatment',
      short: 'Frizz-free, glossy results that last up to 5 months.',
      description: 'Eliminates frizz, reduces drying time by up to 60%, and leaves hair silky and manageable for months. Fully customisable from a light smoothing to a complete bond repair. Blowout included.',
      price: 'From R1 200', duration: '3 – 4 hours',
    },
    {
      id: 4, num: '04',
      name: 'Bridal Hair',
      short: 'Trial and wedding day styling for brides and bridal parties.',
      description: 'From intimate elopements to full bridal parties. We work with you from trial to the morning of your wedding and travel to your venue. Packages for bridesmaids, mothers and flower girls.',
      price: 'From R2 500', duration: 'By arrangement',
    },
    {
      id: 5, num: '05',
      name: 'Hair Extensions',
      short: 'Tape-in or clip-in extensions using 100% Remy human hair.',
      description: 'Add length, volume, or both using Grade A Remy human hair, colour-matched to your own. Applied in one session and maintained every 6–8 weeks. Removal and refit available.',
      price: 'From R1 800', duration: '2 – 3 hours',
    },
    {
      id: 6, num: '06',
      name: 'Scalp & Bond Treatment',
      short: 'Deep conditioning, scalp therapy and Olaplex bond repair.',
      description: 'Designed for over-processed, brittle, or dry hair. Combines Olaplex bond repair with a targeted scalp treatment to restore strength, moisture and shine from root to tip.',
      price: 'From R350', duration: '45 – 60 min',
    },
  ],

  gallery: [
    { id: 1,  src: 'https://picsum.photos/600/800?random=21',  category: 'Colour',     alt: 'Balayage result'       },
    { id: 2,  src: 'https://picsum.photos/800/600?random=22',  category: 'Cuts',       alt: 'Precision cut'         },
    { id: 3,  src: 'https://picsum.photos/600/800?random=23',  category: 'Treatments', alt: 'Keratin treatment'     },
    { id: 4,  src: 'https://picsum.photos/800/600?random=24',  category: 'Colour',     alt: 'Full colour'           },
    { id: 5,  src: 'https://picsum.photos/600/800?random=25',  category: 'Bridal',     alt: 'Bridal updo'          },
    { id: 6,  src: 'https://picsum.photos/800/600?random=26',  category: 'Cuts',       alt: 'Styled blowout'       },
    { id: 7,  src: 'https://picsum.photos/600/800?random=27',  category: 'Colour',     alt: 'Highlights'           },
    { id: 8,  src: 'https://picsum.photos/800/600?random=28',  category: 'Bridal',     alt: 'Bridal trial'         },
    { id: 9,  src: 'https://picsum.photos/600/800?random=29',  category: 'Treatments', alt: 'Bond treatment'       },
    { id: 10, src: 'https://picsum.photos/800/600?random=30',  category: 'Cuts',       alt: 'Textured cut'         },
    { id: 11, src: 'https://picsum.photos/600/800?random=31',  category: 'Colour',     alt: 'Toning result'        },
    { id: 12, src: 'https://picsum.photos/800/600?random=32',  category: 'Treatments', alt: 'Scalp treatment'      },
  ],

  products: [
    {
      id: 1, name: 'Moroccanoil Treatment Original',
      brand: 'Moroccanoil', category: 'Treatments',
      price: 590, originalPrice: 0, badge: 'Best Seller',
      image: 'https://picsum.photos/400/400?random=41',
      size: '100ml',
      description: 'The iconic argan oil-infused treatment that defined a category. Instantly conditions, detangles and adds brilliant shine. A finishing treatment, leave-in conditioner and styling product all in one.',
      benefits: ['Reduces drying time by up to 40%', 'Eliminates frizz and flyaways', 'Adds lasting shine', 'Suitable for all hair types', 'Colour-safe formula'],
      howToUse: 'Apply a small amount to damp or dry hair. Work through mid-lengths to ends. Style as usual. Can be used daily.',
    },
    {
      id: 2, name: 'Olaplex No. 3 Hair Perfector',
      brand: 'Olaplex', category: 'Treatments',
      price: 620, originalPrice: 0, badge: 'Best Seller',
      image: 'https://picsum.photos/400/400?random=42',
      size: '100ml',
      description: 'The at-home bond-building treatment that started the Olaplex revolution. Visibly strengthens and repairs damaged, breaking and brittle hair. Used before shampooing for best results.',
      benefits: ['Repairs broken hair bonds', 'Reduces breakage and brittleness', 'Improves hair strength', 'Safe for colour-treated hair', 'Visible results from first use'],
      howToUse: 'Apply generously to damp, towel-dried hair. Leave for at least 10 minutes (up to 90 min). Rinse, shampoo and condition as normal.',
    },
    {
      id: 3, name: 'Kérastase Nutritive Masquintense',
      brand: 'Kérastase', category: 'Treatments',
      price: 680, originalPrice: 850, badge: 'Sale',
      image: 'https://picsum.photos/400/400?random=43',
      size: '200ml',
      description: 'An intensely nourishing mask for dry, sensitised hair. Rich formula infused with irisome and glucose proteins restores suppleness and luminosity to parched strands.',
      benefits: ['Deep nourishes dry hair', 'Restores softness and suppleness', 'Adds brilliant luminosity', 'Reduces breakage from brushing', 'Visible results from first use'],
      howToUse: 'After shampooing, apply to wet hair from mid-lengths to ends. Leave for 3–5 minutes, then rinse. Use 1–2 times per week.',
    },
    {
      id: 4, name: 'Wella Fusion Intense Repair Mask',
      brand: 'Wella Professionals', category: 'Treatments',
      price: 460, originalPrice: 560, badge: 'Sale',
      image: 'https://picsum.photos/400/400?random=44',
      size: '150ml',
      description: 'A professional-grade reconstruction mask for heavily damaged hair. Powered by amino silk complex and fibrilite silk protein to restore strength, elasticity and smoothness.',
      benefits: ['Reconstructs damaged hair structure', 'Improves elasticity and strength', 'Adds smoothness and manageability', 'Reduces split ends', 'Long-lasting results'],
      howToUse: 'Shampoo first. Apply to wet hair, leave for 5–10 minutes. Use heat for deeper penetration. Rinse well.',
    },
    {
      id: 5, name: 'Redken All Soft Shampoo',
      brand: 'Redken', category: 'Shampoo & Care',
      price: 280, originalPrice: 0, badge: '',
      image: 'https://picsum.photos/400/400?random=45',
      size: '300ml',
      description: 'A hydrating shampoo for dry, brittle hair. Enriched with argan oil and RCT protein, this formula gently cleanses while infusing hair with weightless moisture.',
      benefits: ['Gently cleanses dry, brittle hair', 'Provides weightless moisture', 'Improves softness and flexibility', 'Colour-safe', 'Suitable for daily use'],
      howToUse: 'Apply to wet hair. Massage through scalp and lengths. Rinse thoroughly. Follow with Redken All Soft Conditioner.',
    },
    {
      id: 6, name: 'Redken All Soft Conditioner',
      brand: 'Redken', category: 'Shampoo & Care',
      price: 310, originalPrice: 0, badge: '',
      image: 'https://picsum.photos/400/400?random=46',
      size: '300ml',
      description: 'A deeply softening conditioner for dry, brittle hair. Formulated with argan oil to detangle and smooth, leaving hair silky soft and easy to manage.',
      benefits: ['Deeply conditions dry hair', 'Detangles with ease', 'Adds silky softness', 'Reduces frizz', 'Colour-safe formula'],
      howToUse: 'After shampooing, apply to mid-lengths and ends. Leave for 2–3 minutes, then rinse. For very dry hair, leave up to 5 minutes.',
    },
    {
      id: 7, name: 'Goldwell Colour Brilliance Shampoo',
      brand: 'Goldwell', category: 'Shampoo & Care',
      price: 290, originalPrice: 360, badge: 'Sale',
      image: 'https://picsum.photos/400/400?random=47',
      size: '250ml',
      description: 'A colour-protecting shampoo for vibrant, coloured hair. Intelligent Keratinite technology strengthens the hair surface to protect colour vibrancy and maintain shine.',
      benefits: ['Protects colour vibrancy', 'Strengthens hair surface', 'Maintains brilliant shine', 'Gentle daily cleanser', 'Prolongs colour longevity'],
      howToUse: 'Lather into wet hair. Massage gently and rinse. Follow with Goldwell Colour Brilliance Conditioner for best results.',
    },
    {
      id: 8, name: 'Schwarzkopf BC Repair Rescue Shampoo',
      brand: 'Schwarzkopf Professional', category: 'Shampoo & Care',
      price: 250, originalPrice: 0, badge: 'New',
      image: 'https://picsum.photos/400/400?random=48',
      size: '250ml',
      description: 'A targeted repair shampoo for damaged hair. Micro-protein concentrate bonds with the hair structure to restore strength and resilience with every wash.',
      benefits: ['Repairs and strengthens damaged hair', 'Bonds into the hair structure', 'Suitable for daily use', 'Builds resilience over time', 'Professional salon formula'],
      howToUse: 'Apply to wet hair, lather and rinse. For best results, use with the full BC Repair Rescue range.',
    },
    {
      id: 9, name: 'Olaplex No. 6 Bond Smoother',
      brand: 'Olaplex', category: 'Styling',
      price: 550, originalPrice: 0, badge: 'New',
      image: 'https://picsum.photos/400/400?random=49',
      size: '100ml',
      description: 'A reparative styling cream that eliminates frizz and adds moisture without weighing hair down. Bonds are repaired as you style — works on all hair types.',
      benefits: ['Eliminates frizz and flyaways', 'Repairs bonds while you style', 'Adds moisture without weight', 'Heat protection up to 230°C', 'No-rinse formula'],
      howToUse: 'Apply to damp or dry hair. Work through mid-lengths to ends. Style as usual. Layer with other Olaplex products freely.',
    },
    {
      id: 10, name: 'Sebastian Potion 9 Wearable Treatment',
      brand: 'Sebastian Professional', category: 'Styling',
      price: 360, originalPrice: 0, badge: '',
      image: 'https://picsum.photos/400/400?random=50',
      size: '150ml',
      description: 'A multi-benefit leave-in treatment for smooth, controlled, shiny hair. The 9-in-1 formula conditions, detangles, controls frizz, adds shine and protects from heat.',
      benefits: ['9-in-1 multi-benefit formula', 'Controls frizz and flyaways', 'Adds lasting shine', 'Protects from heat up to 220°C', 'Lightweight, non-greasy finish'],
      howToUse: 'Apply to damp or dry hair. Distribute evenly through mid-lengths and ends. Style as desired.',
    },
    {
      id: 11, name: "Bumble and Bumble Hairdresser's Invisible Oil",
      brand: 'Bumble and Bumble', category: 'Styling',
      price: 520, originalPrice: 620, badge: 'Sale',
      image: 'https://picsum.photos/400/400?random=51',
      size: '100ml',
      description: 'A supremely lightweight dry oil for sleek, glossy hair. Six featherweight oils blended into a formula that gives salon-fresh shine without weight or greasiness.',
      benefits: ['Ultra-lightweight dry oil formula', 'Adds high-shine gloss', 'Heat protection up to 230°C', 'Detangles and smooths', 'Suitable for all hair types'],
      howToUse: 'Apply 1–2 pumps to damp hair before blow-drying, or to dry hair as a finishing touch. Focus on mid-lengths and ends.',
    },
    {
      id: 12, name: 'Tangle Teezer The Ultimate Detangler',
      brand: 'Tangle Teezer', category: 'Tools',
      price: 290, originalPrice: 0, badge: 'New',
      image: 'https://picsum.photos/400/400?random=52',
      size: 'Full Size',
      description: 'The iconic detangling brush that glides through wet or dry hair without tugging or causing breakage. Unique two-tiered tooth technology flexes and bends to protect your hair.',
      benefits: ['Detangles without breakage', 'Works on wet and dry hair', 'Reduces tension on scalp', 'Suitable for all hair types', 'Ergonomic grip design'],
      howToUse: 'Start from the ends and work up through knots. Use wet or dry. Ideal for use with conditioner in the shower.',
    },
  ],

  testimonials: [
    {
      name: 'Thandi M.', location: 'Vereeniging',
      text: 'Came in for a colour correction after a bad at-home bleach job. Adéle fixed everything in one session and my hair has never looked better. She also explained exactly how to maintain it. I won\'t go anywhere else.',
      rating: 5,
    },
    {
      name: 'Riana K.', location: 'Vanderbijlpark',
      text: 'Three years as a client and I still get compliments on my balayage every time. It grows out so beautifully you barely notice the regrowth. Genuinely the best salon in the Vaal.',
      rating: 5,
    },
    {
      name: 'Sharon N.', location: 'Centurion',
      text: 'Booked Noir Studio for my wedding and they were calm, professional and so talented. Four of us were done on time and exactly as planned. My hair held all night. Absolutely worth it.',
      rating: 5,
    },
  ],
}

export type Service     = typeof SITE.services[number]
export type Product     = typeof SITE.products[number]
export type GalleryItem = typeof SITE.gallery[number]
